@echo off
rem This file generated by Jython installer
rem Created on XXX by eytan
rem

set ARGS=

:loop
if [%1] == [] goto end
        set ARGS=%ARGS% %1
        shift
        goto loop
:end



"java.exe" "-Dpython.home=.\src" -classpath "%CLASSPATH%" org.python.util.jython %ARGS%

