@echo off
REM This file generated by Jython installer
REM Created on XXX by eytan

set ARGS=
:loop
if [%1] == [] goto end
        set ARGS=%ARGS% %1
        shift
        goto loop
:end

jython.bat Tools\jythonc\jythonc.py %ARGS%
